#!/usr/bin/env bash
#
# HubFlow - a fork of the git-flow tools to apply Vincent Driessen's
# branching model to working with GitHub
#
# Original blog post presenting this model is found at:
#    http://nvie.com/git-model
#
# The HubFlow documentation is found at:
#    http://datasift.github.com/gitflow/
#
# Feel free to contribute to this project at:
#    http://github.com/datasift/gitflow
#
# Copyright 2010 Vincent Driessen. All rights reserved.
# Copyright 2012 MediaSift Ltd. All rights reserved.
#
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    1. Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#    2. Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY VINCENT DRIESSEN ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL VINCENT DRIESSEN OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are
# those of the authors and should not be interpreted as representing official
# policies, either expressed or implied, of Vincent Driessen.
#

require_git_repo
require_hubflow_initialized
hubflow_load_settings

usage() {
	echo "usage: git hf release [list] [-v]"
	echo "       git hf release start <version> [<base>]"
	echo "       git hf release finish [-sumpk] <version>"
	echo "       git hf release cancel <version>"
	echo "       git hf release push [<version>]"
	echo "       git hf release pull [<version>]"
	echo "       git hf release rename <new-version>"
}

cmd_default() {
	cmd_list "$@"
}

cmd_list() {
	DEFINE_boolean verbose false 'verbose (more) output' v
	parse_args "$@"

	local release_branches
	local current_branch
	local short_names
	release_branches=$(echo "$(git_local_branches)" | grep "^$RELEASE_PREFIX")
	if [ -z "$release_branches" ]; then
		warn "No release branches exist."
                warn ""
                warn "You can start a new release branch:"
                warn ""
                warn "    git hf release start <name> [<base>]"
                warn ""
		exit 0
	fi

	current_branch=$(git_current_branch)
	short_names=$(echo "$release_branches" | sed "s ^$RELEASE_PREFIX  g")

	# determine column width first
	local width=0
	local branch
	for branch in $short_names; do
		local len=${#branch}
		width=$(max $width $len)
	done
	width=$(($width+3))

	local branch
	for branch in $short_names; do
		local fullname=$RELEASE_PREFIX$branch
		local base=$(git merge-base "$fullname" "$DEVELOP_BRANCH")
		local develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
		local branch_sha=$(git rev-parse "$fullname")
		if [ "$fullname" = "$current_branch" ]; then
			printf "* "
		else
			printf "  "
		fi
		if flag verbose; then
			printf "%-${width}s" "$branch"
			if [ "$branch_sha" = "$develop_sha" ]; then
				printf "(no commits yet)"
			else
				local nicename=$(git rev-parse --short "$base")
				printf "(based on $nicename)"
			fi
		else
			printf "%s" "$branch"
		fi
		echo
	done
}

cmd_help() {
	usage
	exit 0
}

parse_args() {
	# parse options
	FLAGS "$@" || exit $?
	eval set -- "${FLAGS_ARGV}"

	# read arguments into global variables
	VERSION=$1
	RELEASE_BRANCH=$RELEASE_PREFIX$VERSION
	RELEASE_FILE="$(git rev-parse --show-toplevel)/.current-release"
}

require_version_arg() {
	if [ "$VERSION" = "" ]; then
		warn "Missing argument <version>"
		usage
		exit 1
	fi
}

require_newversion_arg() {
	if [[ -z $VERSION ]] ; then
		warn "Missing argument <new-version>"
		usage
		exit 1
	fi
}

cmd_start() {
	parse_args "$@"
	if hubflow_is_support_branch ; then
		BASE=$CURRENT_BRANCH
	else
		BASE=$DEVELOP_BRANCH
	fi
	BASE=${3:-$BASE}
	require_version_arg
	local release_tag="$RELEASE_PREFIX$VERSION"

	# sanity checks
	require_remote_available

  # make sure we've never created this release before
	require_branch_absent "$RELEASE_BRANCH"
	require_tag_absent $release_tag
	if has "$ORIGIN/$BASE" "$(git_remote_branches)"; then
		require_branches_equal "$BASE" "$ORIGIN/$BASE"
	fi

	require_clean_working_tree
  hubflow_fetch_latest_changes_from_origin
	require_base_is_on_develop
  git reset --hard origin/develop

	# create branch
	git checkout -b "$RELEASE_BRANCH" "$BASE" || die "Unable to create branch '$RELEASE_BRANCH'"

	# remember where to merge it back to
	git_config_set_branch "$RELEASE_BRANCH" hubflowBase "$BASE"

	# push it back up to remote repo
	hubflow_push_latest_changes_to_origin

	echo
	echo "Summary of actions:"
	echo "- A new branch '$RELEASE_BRANCH' was created, based on '$BASE'"
	echo "- The branch '$RELEASE_BRANCH' has been pushed up to '$ORIGIN/$RELEASE_BRANCH'"
	echo "- You are now on branch '$RELEASE_BRANCH'"
	echo
	echo "Follow-up actions:"
	echo "- Bump the version number now!"
	echo "- Start committing last-minute fixes in preparing your release"
	echo "- When done, run:"
	echo
	echo "     git hf release finish '$VERSION'"
	echo
	echo "  and your changes will be merged back into '$BASE'."
}

cmd_finish() {
	DEFINE_boolean sign false "sign the release tag cryptographically" s
	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
	DEFINE_string message "" "use the given tag message" m
	DEFINE_boolean automessage true "use the tag name as the message" M
	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
	DEFINE_boolean keep false "keep branch after performing finish" k
	DEFINE_boolean notag false "don't tag this release" n

	parse_args "$@"
	require_version_arg

	# make sure that nasty things don't happen if we're not on
	# the release branch at the current time
	RELEASE_BRANCH="$RELEASE_PREFIX$VERSION"

	# sanity checks
	require_branch "$RELEASE_BRANCH"
	require_clean_working_tree
	require_remote_available
  hubflow_fetch_latest_changes_from_origin

  echo "Checking for changes on the remote.."
  local found_updates=`git --no-pager diff $RELEASE_BRANCH..origin/$RELEASE_BRANCH`

  if [ "$found_updates" ]; then
    printf "\nChanges found\n"
    printf "################################################################################\n"
    git --no-pager diff $RELEASE_BRANCH..origin/$RELEASE_BRANCH
    printf "################################################################################\n"
    printf "release branch '%s' has been modified. Update your local branch (answering no will force push and overwrite changes on the remote) (y/N)? " "$RELEASE_BRANCH"
    local should_update
    read should_update
    # Normalize the string so people don't have to guess upper or lower case
    should_update=$(echo $should_update | tr '[:upper:]' '[:lower:]')
    if [ $should_update == "y" ] || [ $should_update == "yes" ]; then
      git pull origin $RELEASE_BRANCH
    else
      git push -f origin $RELEASE_BRANCH
    fi
  fi

	local previous_tag
	if [ -f $RELEASE_FILE ]; then
		previous_tag="$(cat $RELEASE_FILE)"
	else
		last_tag_ref=`git rev-list --tags --skip=1 --max-count=1`
	  previous_tag=`git describe --abbrev=0 --tags $last_tag_ref`
		echo "Falling back to a guessed previous tag ($previous_tag), release notes may be incorrect this release."
	fi

	tagname="$VERSION_PREFIX$VERSION"
	# update the release file
	if [[ $tagname && $RELEASE_FILE ]]; then
		echo "Updating $RELEASE_FILE to $release_tag"
		echo $tagname > $RELEASE_FILE
		git add $RELEASE_FILE
		git commit -m "Updates .current-release to $tagname"
	else
		die "Could not determine the release tag.. Are you sure hubflow was setup properly?"
	fi

  hubflow_push_latest_changes_to_origin
  hubflow_merge_latest_changes_from_origin

	# where are we merging into?
	BASE=$(git_config_get_branch $RELEASE_BRANCH hubflowBase)
  tag_branch="$MASTER_BRANCH"
  additional_branch="$DEVELOP_BRANCH"
  final_branch="$DEVELOP_BRANCH"


	# we need to be up to date before we go any further
	for merge_branch in $tag_branch $additional_branch ; do
		if has "$ORIGIN/$merge_branch" "$(git_remote_branches)"; then
			require_branches_equal "$merge_branch" "$ORIGIN/$merge_branch"
		fi
	done

	# try to merge into the branch we want to tag, first
	# in case a previous attempt to finish this release branch has failed,
	# but the merge into master was successful, we skip it now
	hubflow_local_merge_helper "$RELEASE_BRANCH" "$tag_branch" no_checkout_afterwards no_ff

  if ! git_tag_exists "$tagname"; then
    echo "Creating tag $tagname"
    git checkout "$tag_branch" || die "Could not checkout $tag_branch."
    eval git tag -a "$tagname" -m "\"Released $VERSION\"" || \
    die "Tagging failed. Please run finish again to retry."
  else
    die "The release tag '$tagname' already exists. Delete it and retry again."
  fi

  # now merge from the tag into the additional_branch, if there
  # is one
  # merge from the tag down into the DEVELOP branch
  #
  # this makes the master branch and the new tag a parent
  # of the develop branch, which in turn lets you use
  # 'git describe' on either branch
  #
  # we use 'no_ff' because we want a commit for the merge
  # to appear in the git history
  hubflow_local_merge_helper "$tagname" "$additional_branch" no_ff no_checkout_afterwards

	# switch to our final branch
	hubflow_change_branch "$final_branch"

	# make sure the merge worked before we start deleting stuff
	for merge_branch in $tag_branch $additional_branch ; do
		if [[ $(git rev-list -n2 "$merge_branch..$RELEASE_BRANCH") ]] ; then
			die "release merge into $merge_branch failed"
		fi
	done

	# delete branch
  if [ "$RELEASE_BRANCH" = "$(git_current_branch)" ]; then
    hubflow_change_branch "$MASTER_BRANCH"
  fi
  git branch -D "$RELEASE_BRANCH"

  for merge_branch in $tag_branch $additional_branch ; do
    git push "$ORIGIN" "$merge_branch" || \
    die "Could not push $merge_branch to $ORIGIN."
  done

  # push any new tags
  git push --tags "$ORIGIN" || \
    die "Could not push tags to $ORIGIN."

  # delete the release branch
  git push "$ORIGIN" :"$RELEASE_BRANCH" || \
    die "Could not delete the remote $RELEASE_BRANCH in $ORIGIN."

	echo
	echo "Summary of actions:"
  echo "- Latest objects have been fetched from '$ORIGIN'"
	echo "- Branch '$RELEASE_BRANCH' has been merged into $tag_branch"
  echo "- The release was tagged '$tagname'"
  if [[ -n $additional_branch ]] ; then
    echo "- The tag '$tagname' was merged into $additional_branch"
  fi
  echo "- Branch '$RELEASE_BRANCH' has been deleted"
  echo "- Changed branches and tags have been pushed to '$ORIGIN'"
  echo "- Branch '$RELEASE_BRANCH' in '$ORIGIN' has been deleted."
	echo "- The file '.current-release' has been updated to '$release_tag'"

	echo

  echo "A browser window was opened for drafting a release."
  echo "Please add change log to the description of the release."
  echo
  echo "--------------------------------------------------------"
  echo "|                    RELEASE NOTES                      |"
  echo "--------------------------------------------------------"
  echo
	git --no-pager log --no-merges --pretty='* %s' $previous_tag..$tagname
  git --no-pager log --no-merges --pretty='* %s' $previous_tag..$tagname | pbcopy
  echo
  echo "--------------------------------------------------------"

  REPO_URL=`git remote -v | grep -m1 '^origin' | sed -Ene's#.*(git@[^[:space:]]*).*#\1#p'`
  USER=`echo $REPO_URL | sed -Ene's#git@github.com:([^/]*)/(.*).git#\1#p'`
  REPO=`echo $REPO_URL | sed -Ene's#git@github.com:([^/]*)/(.*).git#\2#p'`

  sleep 4
  open -a "${HUBFLOW_BROWSER:-Google Chrome}" "https://github.com/$USER/$REPO/releases/new?tag=$tagname"
}

cmd_cancel() {
	DEFINE_boolean fetch true "fetch from $ORIGIN before performing cancel" F
	DEFINE_string message "" "use the given tag message" m
	DEFINE_boolean push true "push to $ORIGIN after performing cancel" p
	DEFINE_boolean keep false "keep branch after performing cancel" k
	DEFINE_boolean force false "safety feature; cannot cancel a release without this flag" f
	DEFINE_boolean discard true "drop the changes in this release; do not merge back into develop" d

	parse_args "$@"
	require_version_arg

	# has the user chosen the force flag?
	if noflag force ; then
		warn "To prevent you accidentally cancelling a release, you _must_ use the -f flag"
		warn "with this command"
		exit 1
	fi

	# sanity checks
	require_branch "$RELEASE_BRANCH"
	require_clean_working_tree
	if flag fetch ; then
		hubflow_fetch_latest_changes_from_origin
	fi
	hubflow_change_branch "$RELEASE_BRANCH"
	if flag push ; then
		hubflow_push_latest_changes_to_origin
	fi

	# where did this branch come from?
	BASE=$(git_config_get_branch $RELEASE_BRANCH hubflowBase)
	if [[ $BASE == $MASTER_BRANCH ]] ; then
		# this is a hotfix made from master
		#
		# if we are not discarding it, we will merge it into DEVELOP
		merge_branch="$DEVELOP_BRANCH"
	else
		# this is a release made from a support branch
		#
		# we must merge it back into the support branch
		merge_branch="$BASE"
	fi

	# we only merge into develop if the user hasn't selected the -d flag
	if noflag discard ; then
		if has "$ORIGIN/$merge_branch" $(git_remote_branches); then
			require_branches_equal "$merge_branch" "$ORIGIN/$merge_branch"
		fi

		# try to merge into develop
		hubflow_local_merge_helper "$RELEASE_BRANCH" "$merge_branch" no_ff no_checkout_afterwards

		# push back to remote repo
		if flag push ; then
			hubflow_push_latest_changes_to_origin
		fi
	fi

	# delete the remote branch
	if flag push ; then
		git push "$ORIGIN" :"$RELEASE_BRANCH" || \
			die "Could not delete the remote $RELEASE_BRANCH in $ORIGIN."
	fi

	# delete local branch
	if noflag keep ; then
		# make sure we are back onto develop | support
		hubflow_change_branch "$merge_branch"

		git branch -d "$RELEASE_BRANCH"
	fi

	echo
	echo "Summary of actions:"
	if flag push ; then
		echo "- Latest objects have been fetched from '$ORIGIN'"
	fi
	if noflag discard ; then
		echo "- Release branch has been merged into '$merge_branch'"
		if flag push ; then
			echo "- '$merge_branch' has been pushed to '$ORIGIN'"
		fi
	fi
	if flag push ; then
		echo "- Release branch '$RELEASE_BRANCH' in '$ORIGIN' has been deleted."
	fi
	if flag keep ; then
		echo "- Release branch '$RELEASE_BRANCH' is still available locally"
	else
		echo "- Release branch '$RELEASE_BRANCH' has been deleted locally"
	fi

	echo
}

cmd_publish() {
	git hf push "$@"
}

cmd_pull() {
	git hf pull "$@"
}

cmd_push() {
	git hf push "$@"
}

parse_remote_name() {
	# parse options
	FLAGS "$@" || exit $?
	eval set -- "${FLAGS_ARGV}"

	# read arguments into global variables
	REMOTE=$1
	NAME=$2
	RELEASE_BRANCH=$RELEASE_PREFIX$NAME
}

name_or_current() {
	if [ -z "$NAME" ]; then
		use_current_release_branch_name
	fi
}

avoid_accidental_cross_branch_action() {
	local current_branch=$(git_current_branch)
	if [ "$RELEASE_BRANCH" != "$current_branch" ]; then
		warn "Trying to pull from '$RELEASE_BRANCH' while currently on branch '$current_branch'."
		warn "To avoid unintended merges, hubflow aborted."
		return 1
	fi
	return 0
}

use_current_release_branch_name() {
	local current_branch=$(git_current_branch)
	if startswith "$current_branch" "$RELEASE_PREFIX"; then
		RELEASE_BRANCH=$current_branch
		NAME=${RELEASE_BRANCH#$RELEASE_PREFIX}
	else
		warn "The current HEAD is no release branch."
		warn "Please specify a <name> argument."
		exit 1
	fi
}

cmd_rename() {
	# sort out our args
	parse_args "$@"
	require_newversion_arg
	NEWNAME=$VERSION
	use_current_release_branch_name

	# make sure the new branch has the release prefix
	if ! echo "$NEWNAME" | grep -q "^$HOTFIX_PREFIX" ; then
		NEWNAME="$RELEASE_PREFIX$NEWNAME"
	fi

	# we need to know the current state of $ORIGIN
	hubflow_fetch_latest_changes_from_origin

	# sanity checks
	require_branch "$RELEASE_BRANCH"
	require_branch_absent "$NEWNAME"
	require_branch_absent "$ORIGIN/$NEWNAME"
	require_tag_absent "${NEWNAME#$RELEASE_PREFIX}"

	# keep track of what we did
	local removed_remote=0

	# do it
	git branch -m "$RELEASE_BRANCH" "$NEWNAME" || die "could not rename local branch"
	if git_branch_exists "$ORIGIN/$RELEASE_BRANCH" ; then
		git push $ORIGIN ":$RELEASE_BRANCH" || die "could not delete remote branch '$RELEASE_BRANCH' at $ORIGIN"
		removed_remote=1
	fi
	git push "$ORIGIN" "$NEWNAME" || die "could not push new branch '$NEWNAME' to $ORIGIN"

	# summary
	echo
	echo "Summary of actions:"
	echo "- The local branch '$RELEASE_BRANCH' has been renamed to '$NEWNAME'."
	if [[ $removed_remote == 1 ]] ; then
		echo "- The remote branch '$RELEASE_BRANCH' at $ORIGIN was removed."
	fi
	echo "- The local branch '$NEWNAME' has been pushed to $ORIGIN."
	echo
}
